apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}-service
spec:
  selector:
    app: {{ .Values.service }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.static.name }}
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: {{ .Values.service }}-service
      port:
        number: {{ .Values.port }}
