apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}-deployment
  labels:
    app: {{ .Values.service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
        - name: {{ .Values.service }}-container
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
